services:
  nginx:
    container_name: nginx
    image: nginx:latest # Based on debian:bookworm-slim
    entrypoint: [ "bash", "/tmp/entrypoint.sh" ]
    volumes:
      - ./nginx:/tmp
      - ${CERTS_DIR}:/etc/letsencrypt
      - ./static:/usr/share/nginx/html/static
    networks:
      pong_network:
        ipv4_address: 172.20.0.2
    ports:
      - "${PORT}:80"
      - "${SPORT}:443"
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - frontend
      - authentication
      - game_config
      - game_logic

  frontend:
    container_name: frontend
    image: nginx:latest # Based on debian:bookworm-slim
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      pong_network:
        ipv4_address: 172.20.0.3

  db:
    image: postgres:latest # Based on debian:bookworm-slim
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      pong_network:
        ipv4_address: 172.20.0.4
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:latest # Based on debian:bookworm-slim
    container_name: redis
    environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}

  game_config:
    image: game_config_service
    container_name: game_config
    build: ./backend/game_config_service
    volumes:
     - ./backend/game_config_service:/code
    networks:
      pong_network:
        ipv4_address: 172.20.0.5
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "8001"
    depends_on:
      - db

  game_logic:
    image: game_logic_service
    container_name: game_logic
    build: ./backend/game_logic_service
    volumes:
      - ./backend/game_logic_service:/code
    networks:
      pong_network:
        ipv4_address: 172.20.0.6
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "8002"
    depends_on:
      - db

  game_manager:
    image: game_manager_service # Based on debian:bookworm-slim
    container_name: game_manager
    build: ./backend/game_manager_service
    volumes:
      - ./backend/game_manager_service:/code
    networks:
      pong_network:
        ipv4_address: 172.20.0.8
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "8004"
    depends_on:
      - db

  authentication:
    image: authentication_service # Based on debian:bookworm-slim
    container_name: authentication
    build: ./backend/authentication_service
    volumes:
      - ./backend/authentication_service:/code
      - ./static:/usr/share/static
    networks:
      pong_network:
        ipv4_address: 172.20.0.7
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose: 
      - "8003"
    depends_on:
      - db

networks:
  pong_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
