
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    entrypoint: [ "bash", "/tmp/entrypoint.sh" ]
    volumes:
      - ./nginx:/tmp
      - ${CERTS_DIR}:/etc/letsencrypt
    networks:
      - pong_network
    ports:
      - "$PORT:80"
      - "$SPORT:443"
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - api_gateway
      - game_manager
      - game_lobby
      - game_logic

  frontend:
    container_name: frontend
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - pong_network

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - pong_network
    env_file: .env

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=redis
    #command: ["redis-server", "--requirepass", "redis"]

  api_gateway:
    container_name: api_gateway
    build: ./backend/api_gateway
    volumes:
     - ./backend/game_lobby_service:/code
    env_file: .env
    networks:
      - pong_network
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_PASSWORD=redis
    depends_on:
      - db
      - redis

  game_manager:
    container_name: game_manager
    build: ./backend/game_manager_service
    volumes:
     - ./backend/game_manager_service:/code
    ports:
      - "8002:8002"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  game_logic:
    image: game_logic_service
    container_name: game_logic
    build: ./backend/game_logic_service
    volumes:
      - ./backend/game_logic_service:/code
    env_file: .env
    networks:
      - pong_network
    ports:
      - "8002:8002"
    depends_on:
      - db

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build: ./backend/api_gateway
    volumes:
      - ./backend/api_gateway:/code
    networks:
      - pong_network
    ports:
      - "8003:8003"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_PASSWORD=redis
    depends_on:
      - db

  game_manager:
    image: game_manager_service
    container_name: game_manager
    build: ./backend/game_manager_service
    volumes:
      - ./backend/game_manager_service:/code
    env_file: .env
    networks:
      - pong_network
    ports:
      - "8004:8004"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_PASSWORD=redis
    depends_on:
      - db

networks:
  pong_network:
