services:
  nginx:
    image: nginx:1.25.5
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./content:/usr/share/nginx/html
    ports:
      - "$PORT:80"
    environment:
      - NODE_ENV=$NODE_ENV
