services:
  nginx:
    container_name: nginx
    image: nginx:1.25.5
    entrypoint: [ "bash", "/tmp/entrypoint.sh" ]
    init: true
    volumes:
      - ./nginx:/tmp
      - ./content:/usr/share/nginx/html
      - ${CERTS_DIR}:/etc/letsencrypt
    ports:
      - "$PORT:80"
      - "$SPORT:443"
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_NAME=${SERVER_NAME}
