services:
  nginx:
    container_name: nginx
    image: nginx:latest
    entrypoint: [ "bash", "/tmp/entrypoint.sh" ]
    volumes:
      - ./nginx:/tmp
      - ${CERTS_DIR}:/etc/letsencrypt
    ports:
      - "$PORT:80"
      - "$SPORT:443"
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_NAME=${SERVER_NAME}

  frontend:
    container_name: frontend
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
