version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    entrypoint: [ "bash", "/tmp/entrypoint.sh" ]
    volumes:
      - ./nginx:/tmp
      - ${CERTS_DIR}:/etc/letsencrypt
    ports:
      - "$PORT:80"
      - "$SPORT:443"
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - game_config
      - game_logic

  frontend:
    container_name: frontend
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  game_config:
    container_name: game_config
    build: ./backend/game_config_service
    volumes:
     - ./backend/game_config_service:/code
    ports:
      - "8001:8000"
    command: gunicorn game_config.wsgi:application --bind 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  game_logic:
    container_name: game_logic
    build: ./backend/game_logic_service
    volumes:
      - ./backend/game_logic_service:/code
    ports:
      - "8002:8000"
    command: gunicorn game_logic.wsgi:application --bind 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

