services:
  nginx:
    container_name: nginx
    image: nginx:latest
    entrypoint: [ "bash", "/tmp/entrypoint.sh" ]
    volumes:
      - ./nginx:/tmp
      - ${CERTS_DIR}:/etc/letsencrypt
      - ./static:/usr/share/nginx/html/static
    networks:
      - pong_network
    ports:
      - "${PORT}:80"
      - "${SPORT}:443"
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - game_config
      - game_logic

  frontend:
    container_name: frontend
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - pong_network

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - pong_network
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  game_config:
    image: game_config_service
    container_name: game_config
    build: ./backend/game_config_service
    volumes:
     - ./backend/game_config_service:/code
    networks:
      - pong_network
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "8001"
    depends_on:
      - db

  game_logic:
    image: game_logic_service
    container_name: game_logic
    build: ./backend/game_logic_service
    volumes:
      - ./backend/game_logic_service:/code
    networks:
      - pong_network
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "8002"
    depends_on:
      - db

  authentication:
    image: authentication_service
    container_name: authentication
    build: ./backend/authentication_service
    volumes:
      - ./backend/authentication_service:/code
      - ./static:/usr/share/static
    networks:
      - pong_network
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose: 
      - "8003"
    ports:
      - "8003:8003"
    depends_on:
      - db

networks:
  pong_network:
