# Generated by Django 3.2.25 on 2024-06-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_logic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePosition',
        ),
    ]
