# Generated by Django 3.2.25 on 2024-06-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('local', 'local'), ('remote', 'Remote')], max_length=6),
        ),
    ]
