# Generated by Django 3.2.25 on 2024-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='alias',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
