# Generated by Django 3.2.25 on 2024-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ManyToManyField(related_name='players', to='game_manager.Game'),
        ),
    ]
