# Generated by Django 3.2.25 on 2024-06-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_auto_20240612_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='host_channel_name',
        ),
    ]
