# Generated by Django 3.2.25 on 2024-07-10 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_auto_20240710_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='player1_score',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='player2_score',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
