# Generated by Django 3.2.25 on 2024-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_alter_round_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
