# Generated by Django 3.2.25 on 2024-07-16 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0003_auto_20240716_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 12, 44, 12, 70030, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='mode_is_local',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 16, 12, 44, 43, 702119, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
