# Generated by Django 3.2.25 on 2024-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0003_player_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
