# Generated by Django 3.2.25 on 2024-07-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0004_player_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
    ]
