# Generated by Django 3.2.25 on 2024-06-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_auto_20240611_1300'),
        ('game_manager', '0004_auto_20240614_1343'),
    ]

    operations = [
    ]
