# Generated by Django 3.2.25 on 2024-07-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0004_alter_player_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('completed', 'completed')], default='pending', max_length=10),
        ),
    ]
