# Generated by Django 3.2.25 on 2024-06-26 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0005_merge_0002_auto_20240611_1300_0004_auto_20240614_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='host_ws_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ws_id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
