# Generated by Django 3.2.25 on 2024-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0006_auto_20240626_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(auto_created=True, default='<function uuid4 at 0x7fd9af7cbf70>', editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
