# Generated by Django 3.2.25 on 2024-07-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0006_auto_20240730_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='player1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='player2_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
