# Generated by Django 3.2.25 on 2024-06-26 16:26

from django.db import migrations, models
import game_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0008_alter_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(default=game_manager.models.generate_game_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
