# Generated by Django 3.2.25 on 2024-06-25 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('single', 'Single'), ('tournament', 'Tournament')], max_length=10)),
                ('connection_type', models.CharField(choices=[('local', 'Local'), ('remote', 'Remote')], max_length=10)),
                ('player_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('players', models.JSONField(max_length=20)),
                ('tree', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
