# Generated by Django 3.2.25 on 2024-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth42', '0004_auto_20240628_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id42',
            field=models.IntegerField(null=True),
        ),
    ]
