# Generated by Django 3.2.25 on 2024-07-04 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth42', '0005_auto_20240703_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='userprofiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
