# Generated by Django 3.2.25 on 2024-07-17 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth42.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth42', '0007_userprofile_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(default=oauth42.models.generate_game_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('mode', models.CharField(choices=[('local', 'local'), ('remote', 'Remote')], max_length=6)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('mode_is_local', models.BooleanField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('participants', models.ManyToManyField(related_name='tournaments', through='oauth42.Participation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='mode_is_local',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id42',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='oauth_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('completed', 'completed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id42', models.IntegerField(null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('oauth_id', models.CharField(blank=True, max_length=200, null=True)),
                ('picture_url', models.URLField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('alias', models.CharField(blank=True, max_length=25, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('friends', models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='oauth42.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='oauth42.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oauth42.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='player_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oauth42.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participation',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth42.game'),
        ),
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='oauth42.game'),
        ),
        migrations.AlterField(
            model_name='round',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_rounds', to='oauth42.player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_rounds', to='oauth42.player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='oauth42.player'),
        ),
    ]
