# Generated by Django 3.2.25 on 2024-07-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth42', '0008_auto_20240717_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'managed': False},
        ),
    ]
