# Generated by Django 3.2.25 on 2024-07-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth42', '0009_auto_20240719_1503'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='game_manager_game',
        ),
        migrations.AlterModelTable(
            name='participation',
            table='game_manager_participation',
        ),
        migrations.AlterModelTable(
            name='player',
            table='game_manager_player',
        ),
        migrations.AlterModelTable(
            name='round',
            table='game_manager_round',
        ),
        migrations.AlterModelTable(
            name='tournament',
            table='game_manager_tournament',
        ),
    ]
