# Generated by Django 3.2.25 on 2024-05-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_lobby_lobby_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='lobby_id',
            field=models.CharField(default='<function uuid4 at 0x7fdac41962a0>', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
