# Generated by Django 3.2.25 on 2024-05-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_player_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
