# Generated by Django 3.2.25 on 2024-05-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_round_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='base.game'),
        ),
        migrations.AlterField(
            model_name='round',
            name='player1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='round',
            name='player2',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='base.player'),
        ),
    ]
