name: Deploy to OCI

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh main ${{ vars.PRODUCTION_INSTANCE_IP }}

    - name: Deploy to development
      shell: bash
      if: github.ref == 'refs/heads/development'
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh development ${{ vars.DEVELOPMENT_INSTANCE_IP }}
