name: Deploy to OCI

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: |
        chmod +x ./scripts/deploy.sh
        ./scripts/deploy.sh main ${{ vars.PRODUCTION_INSTANCE_IP }} ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to development
      shell: bash
      if: github.ref == 'refs/heads/development'
      run: |
        chmod +x ./scripts/deploy.sh
        ./scripts/deploy.sh development ${{ vars.DEVELOPMENT_INSTANCE_IP }} ${{ secrets.SSH_PRIVATE_KEY }}
